[[libmpfit]]
arch = "x86_64"
git-tree-sha1 = "5be7cb45e5958f3050444fde2b0d4b01811e7d8f"
libc = "glibc"
os = "linux"

    [[libmpfit.download]]
    sha256 = "d90954993325746977c9683654a09cc25505e0229ffb89b482b3ab46dd1459fc"
    url = "http://wwwuser.oats.inaf.it/calderone/CMPFitBinaries/libmpfit_x64_linux.tar.gz"

[[libmpfit]]
arch = "x86_64"
git-tree-sha1 = "bba8dcf2653333fee812596ddcbf7c695d614457"
os = "macos"

    [[libmpfit.download]]
    sha256 = "5f0d724330ec43eed68303843509cf0fa1b970e6e5bbb768ba44f92fe9a3c138"
    url = "http://wwwuser.oats.inaf.it/calderone/CMPFitBinaries/libmpfit_x64_macos.tar.gz"

[[libmpfit]]
arch = "x86_64"
git-tree-sha1 = "21ba4174eb6b3f2b3191bdcc9cb48d393e4bf7a6"
os = "windows"

    [[libmpfit.download]]
    sha256 = "a3c7ac92bbd5c2624f5b70729277ee63cc8cbca22481cf4b6dcd1047bb03f727"
    url = "http://wwwuser.oats.inaf.it/calderone/CMPFitBinaries/libmpfit_x64_win.tar.gz"
