[[libmpfit]]
arch = "x86_64"
git-tree-sha1 = "f0a96078b3f23cfae705a94c1bb4d7f84faaf1a1"
libc = "glibc"
os = "linux"

    [[libmpfit.download]]
    sha256 = "16fffc40ab7a90e15a283fba967c6fbc9cb2a5ce5e72b1985ba8cbd099fcf0d5"
    url = "http://wwwuser.oats.inaf.it/calderone/CMPFitBinaries/libmpfit_x64_linux.so"
