[[libmpfit14]]
arch = "x86_64"
git-tree-sha1 = "49a7f4cef11ad08ab375503ea62933638396a800"
libc = "glibc"
os = "linux"

    [[libmpfit14.download]]
    sha256 = "ed8d5bd6c38e9e46a33ef63e89f58fd08cc7db1dbc4cceabe8c931ab8e7749a3"
    url = "http://wwwuser.oats.inaf.it/calderone/CMPFitBinaries/libmpfit14_x64_linux.tar.gz"
