[[libmpfit]]
arch = "x86_64"
git-tree-sha1 = "5be7cb45e5958f3050444fde2b0d4b01811e7d8f"
libc = "glibc"
os = "linux"

    [[libmpfit.download]]
    sha256 = "4e82e45f4471668d257c3ffad9191f139d5caaef862989384b3208c3524cd737"
    url = "https://qsfit.inaf.it/qsfitdata/CMPFitBinaries/libmpfit_x64_linux.tar.gz"
[[libmpfit]]
arch = "x86_64"
git-tree-sha1 = "bba8dcf2653333fee812596ddcbf7c695d614457"
os = "macos"

    [[libmpfit.download]]
    sha256 = "65e7b1daf13d6e5ec933d0e71a86e16a2b19be86d30adaa9d8475a6df4494683"
    url = "https://qsfit.inaf.it/qsfitdata/CMPFitBinaries/libmpfit_x64_macos.tar.gz"
[[libmpfit]]
arch = "x86_64"
git-tree-sha1 = "7223c3b488dbc040e43fd4c14e8215d13d3d43f2"
os = "windows"

    [[libmpfit.download]]
    sha256 = "28294e3a1474ddbbefbde1ecbbaf870df52abc7de581384410d771ee8aaa5c7d"
    url = "https://qsfit.inaf.it/qsfitdata/CMPFitBinaries/libmpfit_x64_win.tar.gz"
